### PR TITLE
WIP: fixing salt calcs

### LINKED ISSUE #40: SNMPv3 with DES and MD5 fails: invalid message authentication salt
These parameters are used:
client = NETSNMP::Client.new({host: 'a.b.c.d', port: 161, version: '3', username: 'user', security_level: 3, auth_protocol: 'md5', auth_password: 'Password1', priv_protocol: 'des', priv_password: 'Password1'})
client.get(oid: "1.3.6.1.2.1.1.5.0")

Error: invalid message authentication salt

Testing in Windows and Ubuntu.
The same parameters were validated and work on Ubuntu with a command-line tool.

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
* Adds PDU/v3 message debugging logs.
* Fixes v3 message decoding when security level of receiver differs from sender's.
* Fixes Cisco "out of  time window" v3 handshake.

Closes #40

### CODE REVIEW

File: lib/netsnmp/message.rb [hunk 1]
```diff
@@ -2,41 +2,69 @@
...
+      auth_param = auth_param.value
+      security_parameters.verify(stream.sub(auth_param, AUTHNONE.value), auth_param, security_level: security_level)
 
-      engine_boots = engine_boots.to_i
-      engine_time = engine_time.to_i
+      engine_boots = engine_boots.value.to_i
+      engine_time = engine_time.value.to_i
 
-      encoded_pdu = security_parameters.decode(pdu_payload, salt: priv_param,
+      encoded_pdu = security_parameters.decode(pdu_payload, salt: priv_param.value,
```
Comment (jinxka) [inline lib/netsnmp/message.rb:60]: Missing params: 'security_level: security_level'

Comment (HoneyryderChuck) [reply lib/netsnmp/message.rb:60]: fixed
